users management
ktechEdge/sheelon pull request #10
Opened 2023-09-08 07:09 UTC by MichaelChemo2507

2023-09-08 15:34 UTC, amird55 requested changes
כשמתחילים לעבוד רואים את הבעיות :)
שמות השדות בטבלה שאתה עובד איתן לא תואמים לשמות השדות שיש בקובץ ה-SQL (למשל LANG)
מספר הטלפון וגם מספר תז צריך להיות מחרוזת, STUDY_FIELD צריך להיות TINYINT
זה יגרור קצת שינויים בקוד ההזנה
שדה Password  מוגדר KEY ולכן לא ניתן להזין סיסמה של מישהו אחר. זו טעות ויש לאפשר חופש בנושא
באופן כללי כדאי להוריד את כל נושא FOREIN KEY
עבור UPDATE לא לכלול את הסיסמה
להוסיף נקודת קצה של עדכון סיסמה

אני חושב שיצרתי ענף חדש מהקוד שלך. אתה רואה אותו? (זה היה נראה שלא עשית ענף משלך, אז תעבוד על שלי לשינויים האלה)

2023-09-14 06:22 UTC, MichaelChemo2507 commented
מספר הטלפון וגם מספר תז צריך להיות מחרוזת : אתה מתכוון שצריך לשנות אותם בטבלה?
בנוסף לא הבנתי את החלק האחרון של ההערה, צריך לשנות את הסיסמה לunique ?

2023-09-14 06:24 UTC, MichaelChemo2507 commented
בכללי אני צריך הסבר יותר מפורט  של סוף ההערה :)

2023-09-14 21:06 UTC, amird55 commented
שינויי השדות שהזכרתי - בבסיס הנתונים והקובץ שמתאר אותו
הסיסמה - שהשדה לא יהיה KEY אלא שדה רגיל
עבור העדכון - יש להוציא מהעדכון את הסיסמה (כלומר אני לא צריך להזין סיסמא כדי לעדכן פרטים)
יש להוסיף נקודת קצה חדשה שמשמשת רק עבור עדכון סיסמה
FOREIN KEY זה משהו שאני לא משתמש בו לאחר שפעם אחת זה עשה לי בעיות בגמישות של שלב הפיתוח
אז רשמתי שאפשר לוותר על זה

2023-09-14 22:51 UTC, amird55 commented
בנוסף, עדכנתי עכשיו את הראשי וזה עושה התנגשות איתך. אז תעשה UPDATE

2023-09-15 07:00 UTC, MichaelChemo2507 commented
אמיר שיניתי מה שצריך ודחפתי את הcommit לענף שיש לו pull request פתוח, תבדוק אם אתה יכול לעשות לcommit האחרון שלי review או שאני צריך לסגור אותו ולפתוח pull request חדש, תודה

2023-09-17 20:56 UTC, amird55 approved these changes

2023-09-17 20:56 UTC, merged