Category Full FE Crud && table design
ktechEdge/sheelon pull request #14
Opened 2023-09-21 11:42 UTC by Wild-death17

main table design for Sheelon && responsive Cat crud Page

2023-09-25 17:19 UTC, amird55 requested changes
לחיצה על כפתור עריכה צריכה להקפיץ חלון שבו מזינים את הערכים החדשים
לחיצה על חלון מחיקה צריכה לבקקש אישור פעולה בעזרת פקודת CONFIRM
טופס הוספה צריך להיות מעל הטבלה
תן עיצוב לכפתורים כך שיהיה ברור שזה לחיץ: צבע רקע שונה במצב HOVER וכן CURSOR:POINTER

2023-10-05 19:10 UTC, Wild-death17 commented
Updated And Working 😊👍

2023-10-06 09:19 UTC, amird55 approved these changes

2023-10-06 09:19 UTC, amird55 approved these changes

2023-10-06 09:19 UTC, amird55 approved these changes

2023-10-06 09:19 UTC, merged